### ISSUE TITLE
Issue with outliners

### ISSUE THREAD

**Issue by gkpraveen1988** [influxdata/kapacitor#1064]
Hi Team, 

Facing issues while importing the outliners py file in to the tick scripts. Trying to find out the standard deviation in a series. 
Clone the repository "https://github.com/influxdata/kapacitor/tree/master/udf/agent/examples/outliers" and got the outliers.py file. 
With that, have made the modifications in kapacitor.conf file. 

[udf.functions.outliers]
     prog = "/usr/bin/python"
     args = ["-u", "/tmp/kapacitor_udf/kapacitor/udf/agent/examples/outliers/outliers.py"]
     timeout = "10s"

Wrote a tick script to use that outliner scripts and perform some tasks. 

batch
        |query('''
                SELECT value
                FROM "testdata"."autogen"."drive_info"
        ''')
                .period(1m)
                .every(10s)
        @outliers()
                .field('value')
        |alert()
                .crit(lambda: "value" > 0.0 )
                .StateChangesOnly()
                .log('/var/tmp/kapacitor/outline.log')

The kapacitor definition and enabling went fine without any issues. 

when the query is executed and getting the error in the logs and not alerting in the log files. 

[task_master:main] 2016/11/29 13:48:38 I! closed
[run] 2016/11/29 13:48:38 E! open server: open service *udf.Service: failed to load process info for "outliers": write error: write |1: broken pipe
[run] 2016/11/29 13:48:39 I! Kapacitor starting, version 1.0.2, branch master, commit 1011dba109bf3d83366c87873ec285c7f9140d34
[run] 2016/11/29 13:48:39 I! Go version go1.6.3
[srv] 2016/11/29 13:48:39 I! Kapacitor hostname: 10.0.0.22
[srv] 2016/11/29 13:48:39 I! ClusterID: 4516c272-fd1e-4244-a2fc-ce95b8383e39 ServerID: be981e65-35a6-42c5-8fd7-80ac94c02c3d
[task_master:main] 2016/11/29 13:48:39 I! opened
[srv] 2016/11/29 13:48:39 D! opening service: *udf.Service
[udf] 2016/11/29 13:48:39 I!P Traceback (most recent call last):
[udf] 2016/11/29 13:48:39 I!P   File "/tmp/kapacitor_udf/kapacitor/udf/agent/examples/outliers/outliers.py", line 3, in <module>
[udf] 2016/11/29 13:48:39 I!P     from kapacitor.udf.agent import Agent, Handler
[udf] 2016/11/29 13:48:39 I!P   File "build/bdist.linux-x86_64/egg/kapacitor/udf/agent.py", line 7, in <module>
[udf] 2016/11/29 13:48:39 I!P   File "build/bdist.linux-x86_64/egg/kapacitor/udf/udf_pb2.py", line 6, in <module>
[udf] 2016/11/29 13:48:39 I!P ImportError: cannot import name enum_type_wrapper

not sure how to resolve this issues. Please do suggest me with an solution. Thanks.

**Comment by nathanielc** [comment]
@gkpraveen1988 You need the google protobuf python libraries. There is a setup.py file provided to install the kapacitor python agent. That should help you get the needed deps.

**Comment by gkpraveen1988** [comment]
Hi Nathanielc, Thanks for your input and I was able to fix the issues. Now the outlier script is getting executed explicitly and able to see the process. 

There is an another issue I am facing. I wrote the tick scripts as below to check the std deviation of last 30 points which I have in the test influxdb. 

batch
    |query('''
     SELECT value
     FROM "testdata"."autogen"."drive_info"
     ''')
     .period(1d)
     .every(10s)
    @outlierAvg()
     .field('value')
    |alert()
     .crit(lambda: "value" > 0.0 )
     .StateChangesOnly()
     .log('/var/tmp/kapacitor/outline.log')


In the above I able to call the method field. The OutlierAvg is able to execute the method in the py script. But post execution the value has to stored to another variable. which should be 

@outliersAvg()
.field('value')
.size(30)
.as('mavg')

But when I modify as above, the script is throwing the below error
invalid TICKscript: line 10 char 7: no method or property "as" on *pipeline.UDFNode

and I am unable to see any logs on to the file "var/tmp/kapacitor/outline.log". 

All I need to do is store the output of .outliersAvg to a variable and check that variable in .Alert() section. 
Could you please help in resolving the issue. 

Thanks

**Comment by nathanielc** [comment]
@gkpraveen1988 Are you using the outliers UDF unmodified? The output if the `@outliersAvg` step is a batch of all the discovered outliers, which are identical copies of the points sent into the UDF. Essentially the UDF is a `where` filter node that filters out normal points and only keeps outliers. 

Therefore the `as` property is not supported since there is no computed resutl to return, rather just copies of the original points are returned.

I see that there is a bit of dead code in the UDF that makes it look like it might support an `as` property so I will clean that up.

**Comment by gkpraveen1988** [comment]
Thank you very much Nathanielc, 

Could you help me understanding the |log() method in tick scripts. 
   stream.from()...
      |window()
          .period(10s)
          .every(10s)
      |log()
      |count('value')

Like at what scenario I can use that and if I use like the below. 

    |log()
     .level('INFO')
     .prefix('value')
Just wanted to know what is the use of the above. Please help me in understanding. 

Thanks. 

Regards
Praveen

**Comment by nathanielc** [comment]
See this https://docs.influxdata.com/kapacitor/v1.1/nodes/log_node/#level

But basically it logs the data that passes through the node. The logs appear where ever you have instructed the kapacitord process to send it logs.

**Comment by gkpraveen1988** [comment]
Thank you for the link.. Following the above link, wrote the below tick script for the last 30 records in influxdb, use outliers and log into a file. 

batch
    |query('''
     SELECT value
     FROM "testdata"."autogen"."drive_info"
     ''')
     .period(5d)
     .every(10s)
    @outlierAvg()
     .field('value')
    |log()
     .level('INFO')
     .prefix('value')
    |alert()
     .message('Levedata: {{ index .Fields "lvl" }}; Prefix data {{ index .Fields "value" }}')
     .crit(lambda: "value" > 0.0 )
     .StateChangesOnly()
     .log('/var/tmp/kapacitor/outline.log')

Here is my configuration file. 

[logging]
    # Destination for logs
    # Can be a path to a file or 'STDOUT', 'STDERR'.
    file = "/var/log/kapacitor/kapacitor.log"
    # Logging level can be one of:
    # DEBUG, INFO, WARN, ERROR, or OFF
    level = "DEBUG"

Is there any way we can have a customized logs file in the tick scripts to get the logs.  All I get is the below contents in the log file.

**Comment by nathanielc** [comment]
@gkpraveen1988 That log entry just says that there are no points returned from the outlerAvg UDF, meaning that no outliers were found. As a result nothing was posted to slack since the batch was empty.

**Comment by sousa97** [comment]
Hi guys i have a error that i saw here but I did not make it resolve
I have my TICKscript here:

@tTest()
        // specify the hotend field
        .field('hotend')
        // Keep a 1h rolling window
        .size(3600)
        // pass in the alpha value
        .alpha(alpha)
    |alert()
        .id('hotend')
        .crit(lambda: "pvalue" < alpha)
        .log('/tmp/kapacitor_udf/hotend_failure.log')

but when i run this TICKscript show this error:
invalid TICKscript: line 15 char 6: no method or property "tTest" on *pipeline.WindowNode
Can help me to resolve this issue?

**Comment by sousa97** [comment]
I solve the issue.
The configuration in the kapacitor.conf was no right, so i ajust the diretory to run the udf, but came other issue.
When i run the TICK show me this: 

Post http://localhost:9092/kapacitor/v1/templates: EOF

Please someone can help me to solve this?
