### ISSUE TITLE
Panic in TargetManager.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1353]
This failure just surfaced in the test suite. @goller  Can you take a look?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85cbd1c]

goroutine 65 [running]:
panic(0x986ad40, 0x1aa20008)
	/usr/local/go/src/runtime/panic.go:500 +0x331
github.com/influxdata/kapacitor/vendor/github.com/prometheus/prometheus/retrieval.(*TargetManager).Stop(0x1ae735c0)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/prometheus/prometheus/retrieval/targetmanager.go:83 +0xfc
github.com/influxdata/kapacitor/services/scraper.(*Service).scrape(0x1ac49400)
	/root/go/src/github.com/influxdata/kapacitor/services/scraper/service.go:111 +0x103
created by github.com/influxdata/kapacitor/services/scraper.(*Service).Open
	/root/go/src/github.com/influxdata/kapacitor/services/scraper/service.go:69 +0x133
FAIL	github.com/influxdata/kapacitor/server	0.223s
```

**Comment by goller** [comment]
Fixed in #1354
