### ISSUE TITLE
Panic on closed channel over udf

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/kapacitor#1591]
Hi while working with an UDF  my kapacitor (Kapacitor 1.3.3 (git: master eacb3730de19d7c70b6481f53100c20850d30b8b) has crashed.

These are my UDF  last logs
````
time="2017-09-28 12:10:25" level=info msg="Agent for connection 15 finished"
time="2017-09-28 12:10:25" level=info msg="Starting agent for connection 19"
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"alertId\" values:<type:STRING stringValue:\"LB_NEXUS5K_CPU_001\" > "
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"searchByTag\" values:<type:STRING stringValue:\"switch\" > "
time="2017-09-28 12:10:25" level=info msg="Agent for connection 16 finished"
time="2017-09-28 12:10:25" level=info msg="Starting agent for connection 20"
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"alertId\" values:<type:STRING stringValue:\"LB_NEXUS5K_MEM_001\" > "
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"searchByTag\" values:<type:STRING stringValue:\"switch\" > "
time="2017-09-28 12:10:25" level=info msg="Starting agent for connection 21"
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"alertId\" values:<type:STRING stringValue:\"LE_NEXUS5K_NETIF_001\" > "
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"searchByTag\" values:<type:STRING stringValue:\"switch\" > "
time="2017-09-28 12:10:25" level=info msg="Starting agent for connection 22"
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"alertId\" values:<type:STRING stringValue:\"LE_NEXUS5K_NETIF_002\" > "
time="2017-09-28 12:10:25" level=info msg="Iniciando opciones: name:\"searchByTag\" values:<type:STRING stringValue:\"switch\" > "
time="2017-09-28 12:11:19" level=info msg=" > host,alertid,mon_active,mon_linia,mon_exc,monFilterTagKey,monFilterTagValue"
time="2017-09-28 12:12:10" level=info msg="Agent for connection 19 finished"
time="2017-09-28 12:12:10" level=info msg="Agent for connection 20 finished"
time="2017-09-28 12:12:10" level=fatal msg="read error: read unix /tmp/monInjector.sock->@: read: connection reset by peer"
````
And these the panic on kapacitor

````
panic: send on closed channel

goroutine 5154595 [running]:
github.com/influxdata/kapacitor/edge.(*channelEdge).Collect(0xc4741ceed0, 0x7f8690e972e0, 0xc475019e60, 0xc, 0x17)
        /home/developer/src/gospace/src/github.com/influxdata/kapacitor/edge/edge.go:58 +0x12d
github.com/influxdata/kapacitor/edge.(*streamStatsEdge).Collect(0xc437de0180, 0x7f8690e972e0, 0xc475019e60, 0xc4202779c0, 0xc46ed1cb38)
        /home/developer/src/gospace/src/github.com/influxdata/kapacitor/edge/stats.go:207 +0x4b
github.com/influxdata/kapacitor.(*Edge).Collect(0xc46529b860, 0x7f8690e972e0, 0xc475019e60, 0xc46ed1cae0, 0xc45cd11f90)
        <autogenerated>:611 +0x5d
github.com/influxdata/kapacitor/edge.Forward(0xc4587ddf40, 0x1, 0x1, 0x7f8690e972e0, 0xc475019e60, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/influxdata/kapacitor/edge/forwarding.go:98 +0x61
github.com/influxdata/kapacitor.(*UDFNode).runUDF.func2(0xc42eb14dc0, 0xc46ed1cde0)
        /home/developer/src/gospace/src/github.com/influxdata/kapacitor/udf.go:96 +0xdf
created by github.com/influxdata/kapacitor.(*UDFNode).runUDF
        /home/developer/src/gospace/src/github.com/influxdata/kapacitor/udf.go:102 +0x15f
````

**Comment by nathanielc** [comment]
Thanks we will look into this.

**Comment by regel** [comment]
@nathanielc I can reproduce this behaviour when trying to exit the UDF gracefully during a replay task

UDF is written in Go, using the agent (not the socket) implementation. UDF code is calling close(a.agent.Responses) and then os.Exit(0). I suspect that something is missing to exit the agent UDF gracefully without causing a panic in kapacitord?

In a panic scenario, is it possible that kapacitord starts a brand new UDF agent when the underlying process exits (with zero, or !=0 return value)?
