### ISSUE TITLE
Read : connection reset by peer issue

### ISSUE THREAD

**Issue by anuttamva** [influxdata/kapacitor#1673]
I've just started with tick. After installation, I just checked whether the kapacitor is working fine or not. 

I used command: 
$  kapacitor list tasks

Output:

Get http://localhost:9092/kapacitor/v1/tasks?dot-view=attributes&fields=type&fields=status&fields=executing&fields=dbrps&limit=100&offset=0&pattern=&replay-id=&script-format=formatted: read tcp 127.0.0.1:57134->127.0.0.1:9092: read: connection reset by peer

Not sure how to debug this error and not getting any solutions.

Kapacitor.conf:

[http]
  # HTTP API Server for Kapacitor
  # This server is always on,
  # it serves both as a write endpoint
  # and as the API endpoint for all other
  # Kapacitor calls.
  bind-address = ":9092"
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[[influxdb]]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  default = true
  name = "localhost"
  urls = ["http://localhost:8086"]
  username = "someusername"
  password = "somepassword"

Regards,
Anuttam

**Comment by varadskarmarkar** [comment]
Any update on this unresolved issue? 

I'm also getting this error. I'm using TICK in conjunction with Confluent Kafka, and in order for the brokers to be able to run on localhost:9092, I've changed Kapacitor to run on 9093:

[http]
  # HTTP API Server for Kapacitor
  # This server is always on,
  # it serves both as a write endpoint
  # and as the API endpoint for all other
  # Kapacitor calls.
  bind-address = ":9093"
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

I am getting the same error as @anuttamva when running the kapacitor list, show, etc commands. Where else do I need to change the port from 9092 to 9093 in order for this to work properly?

**Comment by PratikSavadi** [comment]
read tcp [::1]:53520->[::1]:9092: read: connection reset by peer 
same Issue is getting for me . If anyone knows the solution for this issue?

**Comment by mvasquez1981** [comment]
I have a similar issue, anybody find out how to fix it?
```
2022-07-14 14:27:15,151 : INFO  : {} : root : [classifier_startup.py] :enable_classifier_task : in line : [213] : Kapacitor Port is Open for Communication....
Post "http://172.17.0.1:9092/kapacitor/v1/tasks": read tcp 172.20.0.5:50086->172.17.0.1:9092: read: connection reset by peer
Traceback (most recent call last):
  File "/EII/./classifier_startup.py", line 364, in <module>
    main()
  File "/EII/./classifier_startup.py", line 355, in main
    msg, status = kapacitor_classifier.enable_tasks(config,
  File "/EII/./classifier_startup.py", line 297, in enable_tasks
    self.enable_classifier_task(host_name,
  File "/EII/./classifier_startup.py", line 219, in enable_classifier_task
    if subprocess.check_call(define_pointcl_cmd) == SUCCESS:
  File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kapacitor', '-skipVerify', 'define', 'py_point_classifier', '-tick', 'tick_scripts/py_point_classifier.tick']' returned non-zero exit status 3.

```
