### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by geraybos** [influxdata/kapacitor#1693]
Kapacitor 1.3.3 on Windows

```
kapacitord -config custom.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2017/11/24 19:33:06 Using configuration at: custom.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x5ada1d]

goroutine 161 [running]:
panic(0x1d23000, 0xc042010080)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/influxdata/kapacitor/services/replay.(*Service).doRecordStream(0xc042239ce0, 0xc04221b530, 0x24, 0x0, 0x0, 0xed1a9fad7, 0xc03afa09a8, 0x2ed2e20, 0xc0423f7420, 0x1, ...)
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:1256 +0x11d
github.com/influxdata/kapacitor/services/replay.(*Service).handleRecordStream.func1(0xc042475d80, 0xc042239ce0, 0xc0424dad40, 0xc0424db240, 0xc04221b530, 0x24, 0xc0426e78c0, 0x39, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:622 +0x12c
created by github.com/influxdata/kapacitor/services/replay.(*Service).handleRecordStream
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:624 +0x4f0
```

**Comment by nathanielc** [comment]
This looks like its possibly a duplicate of #916 which was fixed in #1542. The 1.4.0 release contains that fix. Can you confirm?

Version 1.4.0 was released today, the downloads page should be updated soon.
