### ISSUE TITLE
kapacitord config command panics

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/kapacitor#1697]
[kapacitor.conf.txt](https://github.com/influxdata/kapacitor/files/1509385/kapacitor.conf.txt)
In cmd/kapacitord/main.go:132 it would appear that the command 'config' should print out a configuration to the console, as is the case with influxd and telegraf.  However, when I try this on the latest nightly build, it panics as follows. 

panic: unexpected reflect.Kind: func [recovered]

Console messages from latest attempts:
```
karl@algonquin:~/Downloads/influxdata$ kapacitord version
Kapacitor 1.5.0~n201711280812 (git: master a1a60f2e560fd89f011aabc0e5eb82e277b668a4)
karl@algonquin:~/Downloads/influxdata$ kapacitord config
2017/11/28 10:55:54 Merging with configuration at: /etc/kapacitor/kapacitor.conf
panic: unexpected reflect.Kind: func [recovered]
    panic: unexpected reflect.Kind: func

goroutine 1 [running]:
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).safeEncode.func1(0xc420641ba0)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:101 +0xa9
panic(0x1d00b40, 0xc420537a40)
    /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.tomlTypeOfGo(0x1dac900, 0xc420337e98, 0x193, 0xb, 0x1dac900)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:420 +0x547
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eStruct.func1(0x33ac5e0, 0x20c1980, 0x20c1980, 0xc420337e00, 0x199, 0x0, 0x0, 0x0)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:338 +0x168
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eStruct(0xc420641cb0, 0xc4205377a0, 0x1, 0x1, 0x20c1980, 0xc420337e00, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:345 +0x140
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eMapOrStruct(0xc420641cb0, 0xc4205377a0, 0x1, 0x1, 0x20c1980, 0xc420337e00, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:260 +0xaa
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eArrayOfTables(0xc420641cb0, 0xc4205377a0, 0x1, 0x1, 0x1e52140, 0xc42024da98, 0x197)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:237 +0x300
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).encode(0xc420641cb0, 0xc4205377a0, 0x1, 0x1, 0x1e52140, 0xc42024da98, 0x197)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:129 +0x3ac
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eStruct.func2(0xc42039a600, 0x2b, 0x40)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:371 +0x38c
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eStruct(0xc420641cb0, 0x3427b00, 0x0, 0x0, 0x21492e0, 0xc42024d800, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:375 +0x25c
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eMapOrStruct(0xc420641cb0, 0x3427b00, 0x0, 0x0, 0x21492e0, 0xc42024d800, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:260 +0xaa
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).eTable(0xc420641cb0, 0x3427b00, 0x0, 0x0, 0x21492e0, 0xc42024d800, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:252 +0xbd
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).encode(0xc420641cb0, 0x3427b00, 0x0, 0x0, 0x21492e0, 0xc42024d800, 0x199)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:149 +0x6d4
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).safeEncode(0xc420641cb0, 0x3427b00, 0x0, 0x0, 0x21492e0, 0xc42024d800, 0x199, 0x0, 0x0)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:104 +0xac
github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml.(*Encoder).Encode(0xc420641cb0, 0x1ede2a0, 0xc42024d800, 0xc420530000, 0x1000)
    /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/BurntSushi/toml/encode.go:88 +0xca
github.com/influxdata/kapacitor/cmd/kapacitord/run.(*PrintConfigCommand).Run(0xc4203a5890, 0xc42000c070, 0x0, 0x0, 0x0, 0x1e7f900)
    /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/config_command.go:62 +0x4cd
main.(*Main).Run(0xc420549400, 0xc42000c070, 0x0, 0x0, 0x0, 0x1c7f8c0)
    /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:133 +0xe0e
main.main()
    /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:42 +0xef 
```

**Comment by karel-rehor** [comment]
Note, that I first encountered this last week on a local build of 1.4-RC1.

**Comment by desa** [comment]
Found where the issue is coming from, its the `mqtt` section. Going to investigate why specifically now.
