### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by devilldog** [influxdata/kapacitor#185]
Hi, trying to test out kapacitor, following the tut @ https://docs.influxdata.com/kapacitor/v0.2/introduction/getting_started/
I get the following error, dont really know anything about go or i would try to debug further.
cheers!
rob
```
# kapacitor define -name load_longterm -type stream -tick cpu_alert.tick  -dbrp collectd
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*dbrps).Set(0xc858a0, 0x7fff9fab98bc, 0x8, 0x0, 0x0)
        /gopath/src/github.com/influxdata/kapacitor/cmd/kapacitor/main.go:358 +0x323
flag.(*FlagSet).parseOne(0xc82001a660, 0x9d5a01, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:881 +0xdd9
flag.(*FlagSet).Parse(0xc82001a660, 0xc82000a0c0, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/flag/flag.go:900 +0x6e
main.main()
        /gopath/src/github.com/influxdata/kapacitor/cmd/kapacitor/main.go:107 +0xa67

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by nathanielc** [comment]
@devilldog The error is that the `dbrp` flag is invalid. It needs to be of the form `dbname.rpname`. The value `collectd` is invalid and should probably be something like `collectd.default`. I'll fix the panic so that it returns a valid error explaining the correct format.
 Thanks for the report.
