### ISSUE TITLE
Defining Template using API gives error

### ISSUE THREAD

**Issue by arushigangrade** [influxdata/kapacitor#1966]
I have encountered an issue while defining templates using the Kapacitor apis. Whenever I try to define a template, by doing a POST request, I get an error message with error code 400-Bad Request and the message-“template <template name>already exists”. I have tested this using Postman. I bring down the whole environment before starting and even used couple weird names just to be sure that I am not using any repetitive name, but the result remains the same.

The json I am sending for template is-

{
    "id" : "Threshold_Template111115",
    "type" : "stream",
    "script": "// Which measurement to consume\nvar measurement string\n\nvar ABC lambda\n\nvar orgGroup lambda\n\nvar tenantId lambda\n\nvar where_filter = lambda: ABC AND orgGroup AND tenantId\n\n// Optional list of group by dimensions\nvar groups = [*]\n\n// Which field to process\nvar field string\n\n// Critical criteria\nvar crit lambda\n\nstream\n    |from()\n        .measurement(measurement)\n        .where(where_filter)\n        .groupBy(groups)\n    |alert()\n        .stateChangesOnly()\n        .crit(crit)\n        .tcp('localhost:80')\n"
}

**Comment by arushigangrade** [comment]
If it helps, I am using Kapacitor 1.4 version.

**Comment by arushigangrade** [comment]
I have tested it with Kapacitor 1.5 version as well and I am still getting the same error.

**Comment by arushigangrade** [comment]
I also found out that this Kapacitor call fails sometimes, stating connection error. When I retry it goes through and gives the above mentioned "already exists" error. I have a single Kapacitor instance, and no other calls- posting an alert task, patching an existing task etc give any error.

**Comment by arushigangrade** [comment]
Thanks for getting back faskiri. The output is-

curl -s <kapacitor-host>/kapacitor/v1/templates | json_pp | grep '"id" :'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
         "id" : "Threshold_Template",

**Comment by faskiri** [comment]
Your script is causing kapacitor to crash, here's the output, I'll update the thread in a while w/ the cause (if I can find it)

```
ts=2018-06-27T07:53:35.206Z lvl=error msg="2018/06/27 07:53:35 http: panic serving 10.117.20.154:46928: runtime error: invalid memory address or nil pointer dereference\ngoroutine 68502 [running]:\nnet/http.(*conn).serve.func1(0xc420159e00)\n\t/usr/local/go/src/net/http/server.go:1726 +0xd0\npanic(0x1d76ec0, 0x341d3f0)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/influxdata/kapacitor/tick/ast.(*LambdaNode).Format(0xc42af17260, 0xc42862d030, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/influxdata/kapacitor/tick/ast/node.go:1632 +0x93\ngithub.com/influxdata/kapacitor/tick/ast.(*BinaryNode).Format(0xc42a96c230, 0xc42862d030, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/influxdata/kapacitor/tick/ast/node.go:542 +0xb3\ngithub.com/influxdata/kapacitor/tick/ast.(*BinaryNode).Format(0xc42a96c280, 0xc42862d030, 0x0, 0x0, 0x1c08201)\n\t/root/go/src/github.com/influxdata/kapacitor/tick/ast/node.go:542 +0xb3\ngithub.com/influxdata/kapacitor/tick/ast.(*LambdaNode).ExpressionString(0xc42af16f60, 0xc423bcecf0, 0x1c082a0)\n\t/root/go/src/github.com/influxdata/kapacitor/tick/ast/node.go:1649 +0x71\ngithub.com/influxdata/kapacitor/services/task_store.(*Service).convertToClientVarFromTick(0xc420159ae0, 0x1f4ddc0, 0xc42af16f60, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:1278 +0x710\ngithub.com/influxdata/kapacitor/services/task_store.(*Service).convertToClientVarsFromTick(0xc420159ae0, 0xc42af17230, 0x18, 0x0, 0xc427068000)\n\t/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:1322 +0x1b9\ngithub.com/influxdata/kapacitor/services/task_store.(*Service).convertTemplate(0xc420159ae0, 0xc42e1a3420, 0x18, 0x0, 0xc427068000, 0x1cd, 0x0, 0x0, 0xbec4ee7fcbea0b2d, 0x3017765b26ff, ...)\n\t/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:1468 +0x186\ngithub.com/influxdata/kapacitor/services/task_store.(*Service).handleCreateTemplate(0xc420159ae0, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:1725 +0x3c4\ngithub.com/influxdata/kapacitor/services/task_store.(*Service).(github.com/influxdata/kapacitor/services/task_store.handleCreateTemplate)-fm(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:175 +0x48\ngithub.com/influxdata/kapacitor/services/httpd.authorize.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200, 0x20f1bda, 0xa, 0x1, 0x3458f30, 0x0, 0x0, 0xc4205bca80)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:722 +0xe9\ngithub.com/influxdata/kapacitor/services/httpd.authenticate.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:587 +0xb45\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1c00, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.jsonContent.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:826 +0xb1\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1c20, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.gzipFilter.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:812 +0x22d\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1c40, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.versionHeader.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:835 +0xbc\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1c60, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.cors.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:868 +0x102\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1c80, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.requestID.func1(0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:878 +0x124\nnet/http.HandlerFunc.ServeHTTP(0xc4205b1cc0, 0x22aa760, 0xc42e5a73a0, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.logHandler.func1(0x22aa760, 0xc42e5a7380, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:886 +0xdf\nnet/http.HandlerFunc.ServeHTTP(0xc420491020, 0x22aa760, 0xc42e5a7380, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.recovery.func1(0x22b29a0, 0xc42b2ea000, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:895 +0xed\nnet/http.HandlerFunc.ServeHTTP(0xc420491050, 0x22b29a0, 0xc42b2ea000, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\ngithub.com/influxdata/kapacitor/services/httpd.(*ServeMux).ServeHTTP(0xc42031d170, 0x22b29a0, 0xc42b2ea000, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/mux.go:163 +0x130\ngithub.com/influxdata/kapacitor/services/httpd.(*Handler).ServeHTTP(0xc420366480, 0x22b29a0, 0xc42b2ea000, 0xc424aa9200)\n\t/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:373 +0xd4\nnet/http.serverHandler.ServeHTTP(0xc426fef790, 0x22b29a0, 0xc42b2ea000, 0xc424aa9200)\n\t/usr/local/go/src/net/http/server.go:2694 +0xbc\nnet/http.(*conn).serve(0xc420159e00, 0x22b5820, 0xc428030440)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2795 +0x27b\n" service=http service=httpd_server_errors
```

**Comment by faskiri** [comment]
The issue is due to lambda: lamba kind of usage you have. I could repro the same in a unit test as well, this is a bug in the script parsing code

**Comment by arushigangrade** [comment]
Hi faskiri.
Sorry for the super late reply. I missed out on replying and then forgot about it. 
Has this bug been reported and is being tracked somewhere.?
