### ISSUE TITLE
panic: cannot create a kafka writer with an empty topic"

### ISSUE THREAD

**Issue by CoderOverflow** [influxdata/kapacitor#2016]
Hi,

C:\tick_win\kapacitor-1.5.0-1>kapacitord -config C:\tick_win\kapacitor-1.5.0-1\k
apacitor.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::
'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##:
 ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##:
 ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##:
 ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##:
 ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##:
 ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######::
 ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::
..:::::..::

2018/08/09 13:04:55 Using configuration at: C:\tick_win\kapacitor-1.5.0-1\kapaci
tor.conf
panic: cannot create a kafka writer with an empty topic

goroutine 193 [running]:
github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go.NewWriter(0
xc042571170, 0x3, 0x3, 0x0, 0x0, 0xc0420fe930, 0x2300e40, 0xc0426c0a40, 0x0, 0x0
, ...)
        /root/go/src/github.com/influxdata/kapacitor/vendor/github.com/segmentio
/kafka-go/writer.go:169 +0x39b
github.com/influxdata/kapacitor/services/kafka.(*Cluster).writer(0xc0421e33f0, 0
x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:6
3 +0x291
github.com/influxdata/kapacitor/services/kafka.(*Cluster).WriteMessage(0xc0421e3
3f0, 0x0, 0x0, 0xc04239d240, 0xb, 0x10, 0xc042885500, 0x688, 0x688, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:3
9 +0x64
github.com/influxdata/kapacitor/services/kafka.(*handler).Handle(0xc0425f68c0, 0
xc042009c20, 0x1b, 0xc04239cf30, 0xb, 0xc042283340, 0x13, 0xc042386a80, 0x33f, 0
x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:2
65 +0x2c4
github.com/influxdata/kapacitor/alert.(*bufHandler).run(0xc04234c240)
        /root/go/src/github.com/influxdata/kapacitor/alert/topics.go:440 +0x81
github.com/influxdata/kapacitor/alert.newHandler.func1(0xc04234c240)
        /root/go/src/github.com/influxdata/kapacitor/alert/topics.go:397 +0x5e
created by github.com/influxdata/kapacitor/alert.newHandler
        /root/go/src/github.com/influxdata/kapacitor/alert/topics.go:395 +0xf9

C:\tick_win\kapacitor-1.5.0-1>

I ran kapacitor1.5 on windows server 2003.
I set my tickscript as following.
stream
    |from()
        .measurement('win_cpu')
    |alert()
        .crit(lambda: "Percent_Processor_Time" > 90)
        .message('Hey, check your CPU')
        .kafka()
        .cluster('kafka01')
        .kafkaTopic('cpu-alerts')

When the alertNode is executed, kapacitor got down and show the message that "
panic: cannot create a kafka writer with an empty topic"

How to solve this problem?

**Comment by CoderOverflow** [comment]
Hi,

C:\tick_win\kapacitor-1.5.0-1>kapacitord -config C:\tick_win\kapacitor-1.5.0-1\k
apacitor.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::
'########::
##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##:
##.... ##:
##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##:
##:::: ##:
#####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##:
########::
##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##:
##.. ##:::
##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##:
##::. ##::
##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######::
##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::
..:::::..::

2018/08/09 13:04:55 Using configuration at: C:\tick_win\kapacitor-1.5.0-1\kapaci
tor.conf
panic: cannot create a kafka writer with an empty topic

goroutine 193 [running]:
github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go.NewWriter(0
xc042571170, 0x3, 0x3, 0x0, 0x0, 0xc0420fe930, 0x2300e40, 0xc0426c0a40, 0x0, 0x0
, ...)
/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/segmentio
/kafka-go/writer.go:169 +0x39b
github.com/influxdata/kapacitor/services/kafka.(*Cluster).writer(0xc0421e33f0, 0
x0, 0x0, 0x0, 0x0, 0x0)
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:6
3 +0x291
github.com/influxdata/kapacitor/services/kafka.(*Cluster).WriteMessage(0xc0421e3
3f0, 0x0, 0x0, 0xc04239d240, 0xb, 0x10, 0xc042885500, 0x688, 0x688, 0x0, ...)
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:3
9 +0x64
github.com/influxdata/kapacitor/services/kafka.(*handler).Handle(0xc0425f68c0, 0
xc042009c20, 0x1b, 0xc04239cf30, 0xb, 0xc042283340, 0x13, 0xc042386a80, 0x33f, 0
x0, ...)
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:2
65 +0x2c4
github.com/influxdata/kapacitor/alert.(*bufHandler).run(0xc04234c240)
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:440 +0x81
github.com/influxdata/kapacitor/alert.newHandler.func1(0xc04234c240)
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:397 +0x5e
created by github.com/influxdata/kapacitor/alert.newHandler
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:395 +0xf9

C:\tick_win\kapacitor-1.5.0-1>

I ran kapacitor1.5 on windows server 2003.
I set my tickscript as following.
stream
|from()
.measurement('win_cpu')
|alert()
.crit(lambda: "Percent_Processor_Time" > 90)
.message('Hey, check your CPU')
.kafka()
.cluster('kafka01')
.kafkaTopic('cpu-alerts')

When the alertNode is executed, kapacitor got down and show the message that "
panic: cannot create a kafka writer with an empty topic"

How to solve this problem?

**Comment by CoderOverflow** [comment]
fixed in v1.5.1
