### ISSUE TITLE
"Deadman" interval = 0s will crash kapacitor

### ISSUE THREAD

**Issue by wcannon** [influxdata/kapacitor#2281]
To reproduce:

In chronograf create a tick script that uses Deadman.

Set interval = 0s

Save tick script

In testing this using the kapacitor container the container will exit on crash.

Looks like it might be a divide by zero bug (e.g.  threshold / interval)

**Comment by russorat** [comment]
@wcannon thanks for the issue. A deadman of 0s doesn't really make much sense but the error shouldn't happen either way.

**Comment by sivascu** [comment]
I have a strange feeling I am having the same issue. Can you guys point me to some info on how to disable the check so Kapacitor would actually start again ?

My current error is:
```
May  6 12:13:06 kapacitor01 kapacitord: 2020/05/06 12:13:06 Using configuration at: /etc/kapacitor/kapacitor.conf
May  6 12:13:59 kapacitor01 kapacitord: panic: non-positive interval for NewTicker
May  6 12:13:59 kapacitor01 kapacitord: goroutine 67092 [running]:
May  6 12:13:59 kapacitor01 kapacitord: time.NewTicker(0x0, 0xed644a107)
May  6 12:13:59 kapacitor01 kapacitord: /usr/local/go/src/time/tick.go:23 +0x147
May  6 12:13:59 kapacitor01 kapacitord: github.com/influxdata/kapacitor.(*StatsNode).runStats(0xc1fef7c140, 0x0, 0x0, 0x0, 0x0, 0x0)
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/stats.go:44 +0x307
May  6 12:13:59 kapacitor01 kapacitord: github.com/influxdata/kapacitor.(*node).start.func1(0xc1fef7c140, 0x0, 0x0, 0x0)
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/node.go:186 +0x9d
May  6 12:13:59 kapacitor01 kapacitord: created by github.com/influxdata/kapacitor.(*node).start
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/node.go:164 +0x5d
May  6 12:13:59 kapacitor01 systemd: kapacitor.service: main process exited, code=exited, status=2/INVALIDARGUMENT

```
I tried changing kapacitor.db with a boltdb browser, but at that point the error changes to:
```
May  6 12:01:37 kapacitor01 kapacitord: ..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
May  6 12:01:37 kapacitor01 kapacitord: 2020/05/06 12:01:37 Using configuration at: /etc/kapacitor/kapacitor.conf
May  6 12:02:30 kapacitor01 kapacitord: run: open server: open service *task_store.Service: no key exists
May  6 12:02:30 kapacitor01 systemd: kapacitor.service: main process exited, code=exited, status=1/FAILURE
May  6 12:02:30 kapacitor01 systemd: Unit kapacitor.service entered failed state.
May  6 12:02:30 kapacitor01 systemd: kapacitor.service failed.
May  6 12:02:30 kapacitor01 systemd: kapacitor.service holdoff time over, scheduling restart.
May  6 12:02:30 kapacitor01 systemd: Stopped Time series data processing engine..
```

Any help would be appreciated.

Kr,
Stefan

**Comment by docmerlin** [comment]
Looks like a stats node with a non prositive duration will exhibit the same behavior.
