### ISSUE TITLE
Panic when divide by zero

### ISSUE THREAD

**Issue by ngohoa211** [influxdata/kapacitor#2329]
i have an tick script:
```
var db = 'telegraf'
var rp = 'autogen'

var measurement = 'mongo_cluster'

var groupBy = ['customer', 'environment', 'project']

var whereFilter = lambda: TRUE

var name = 'backend_mongodb_cluster_health'

var idVar = name + '-{{.Group}}'

var message = 'MongoDB Cluster on project {{ index .Tags "project" }} is DOWN'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var triggerType = 'threshold'

var crit = 50

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: 100 * ("total_members" - "active_members") / "total_members")
        .as('value')
        .quiet()

var trigger = data
    |alert()
        .crit(lambda: "value" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .stateChangesOnly(30s)
        .log('/tmp/mongodb.log')
```
when data go to steam with "total_members" = 0 . it go to panic:
```
panic: runtime error: integer divide by zero
goroutine 290 [running]:
github.com/influxdata/kapacitor/tick/stateful.glob..func51(0xc000fce900, 0xc000de1e90, 0x25317a0, 0xc002935e80, 0x2531b20, 0xc00297aeb0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/evaluation_funcs.go:1037 +0x31c
github.com/influxdata/kapacitor/tick/stateful.(*EvalBinaryNode).eval(0xc002935e40, 0xc000fce900, 0xc000de1e90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/eval_binary_node.go:254 +0xba
github.com/influxdata/kapacitor/tick/stateful.(*EvalBinaryNode).evaluateDynamicNode(0xc002935e40, 0xc000fce900, 0xc000de1e90, 0x25317a0, 0xc002935e80, 0x2531b20, 0xc00297aeb0, 0x0, 0x0, 0x0, ...)
         /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/eval_binary_node.go:312 +0x330
github.com/influxdata/kapacitor/tick/stateful.(*EvalBinaryNode).eval(0xc002935e40, 0xc000fce900, 0xc000de1e90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
         /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/eval_binary_node.go:254 +0xba
github.com/influxdata/kapacitor/tick/stateful.(*EvalBinaryNode).EvalInt(0xc002935e40, 0xc000fce900, 0xc000de1e90, 0xc0007df202, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/eval_binary_node.go:231 +0x5a
github.com/influxdata/kapacitor/tick/stateful.(*expression).EvalInt(...)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/expr.go:72
github.com/influxdata/kapacitor/tick/stateful.(*expression).Eval(0xc000fce8a0, 0xc000fce900, 0x2, 0x2, 0x7fa4553f0b30, 0xc0004819e0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/stateful/expr.go:99 +0x22b
github.com/influxdata/kapacitor.(*EvalNode).eval(0xc00291d600, 0xc000fca370, 0x1, 0x1, 0x7fa4553f0c58, 0xc0004819e0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/eval.go:104 +0xe90
github.com/influxdata/kapacitor.(*evalGroup).doEval(0xc000fce8c0, 0x7fa4553f0c58, 0xc0004819e0, 0x7fa4553f0c58)
         /home/ubuntu/go/src/github.com/influxdata/kapacitor/eval.go:210 +0x61
github.com/influxdata/kapacitor.(*evalGroup).Point(0xc000fce8c0, 0x253f040, 0xc0004819e0, 0xb904ec, 0x1dfef20, 0xc000f705d0, 0xc000b2c340)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/eval.go:203 +0x7e
github.com/influxdata/kapacitor/edge.(*timedForwardReceiver).Point(0xc000fce8e0, 0x253f040, 0xc000481950, 0x0, 0x0, 0x2526ee0, 0xc000de1ec0)
         /home/ubuntu/go/src/github.com/influxdata/kapacitor/edge/timed.go:62 +0x62
github.com/influxdata/kapacitor/edge.(*forwardingReceiver).Point(0xc000de1ec0, 0x253f040, 0xc000481950, 0xc000de1e60, 0x0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/edge/forwarding.go:76 +0x4c
github.com/influxdata/kapacitor/edge.(*groupedConsumer).Point(0xc001066240, 0x253f040, 0xc000481950, 0x253f040, 0xc000481950)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/edge/grouped.go:107 +0x151
github.com/influxdata/kapacitor/edge.(*consumer).Consume(0xc000d34440, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/edge/consumer.go:62 +0x38e
github.com/influxdata/kapacitor/edge.(*groupedConsumer).Consume(0xc001066240, 0x2190b14, 0x13)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/edge/grouped.go:51 +0x33
github.com/influxdata/kapacitor.(*EvalNode).runEval(0xc00291d600, 0x0, 0x0, 0x0, 0x2e33, 0x2140540)
       /home/ubuntu/go/src/github.com/influxdata/kapacitor/eval.go:72 +0x1bb
 github.com/influxdata/kapacitor.(*node).start.func1(0xc00291d600, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/influxdata/kapacitor/node.go:186 +0x89
created by github.com/influxdata/kapacitor.(*node).start
      /home/ubuntu/go/src/github.com/influxdata/kapacitor/node.go:164 +0x5d
```
Make kapacitord restart over and over again. Even difficult to disable that tickscript.

I know i can workaround by add WHERE condition check if "total_members" !=0 . But it just a trick. All service down just because adding one script seem like unacceptable. 
Can you fix that? make it not panic again?

**Comment by docmerlin** [comment]
eval should recover from these sorts of panics and turn them into errors.

**Comment by sivascu** [comment]
I have a strange feeling I am having the same issue. Can you guys point me to some info on how to disable the check so Kapacitor would actually start again ?

My current error is:
```
May  6 12:13:06 kapacitor01 kapacitord: 2020/05/06 12:13:06 Using configuration at: /etc/kapacitor/kapacitor.conf
May  6 12:13:59 kapacitor01 kapacitord: panic: non-positive interval for NewTicker
May  6 12:13:59 kapacitor01 kapacitord: goroutine 67092 [running]:
May  6 12:13:59 kapacitor01 kapacitord: time.NewTicker(0x0, 0xed644a107)
May  6 12:13:59 kapacitor01 kapacitord: /usr/local/go/src/time/tick.go:23 +0x147
May  6 12:13:59 kapacitor01 kapacitord: github.com/influxdata/kapacitor.(*StatsNode).runStats(0xc1fef7c140, 0x0, 0x0, 0x0, 0x0, 0x0)
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/stats.go:44 +0x307
May  6 12:13:59 kapacitor01 kapacitord: github.com/influxdata/kapacitor.(*node).start.func1(0xc1fef7c140, 0x0, 0x0, 0x0)
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/node.go:186 +0x9d
May  6 12:13:59 kapacitor01 kapacitord: created by github.com/influxdata/kapacitor.(*node).start
May  6 12:13:59 kapacitor01 kapacitord: /root/go/src/github.com/influxdata/kapacitor/node.go:164 +0x5d
May  6 12:13:59 kapacitor01 systemd: kapacitor.service: main process exited, code=exited, status=2/INVALIDARGUMENT

```
I tried changing kapacitor.db with a boltdb browser, but at that point the error changes to:
```
May  6 12:01:37 kapacitor01 kapacitord: ..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
May  6 12:01:37 kapacitor01 kapacitord: 2020/05/06 12:01:37 Using configuration at: /etc/kapacitor/kapacitor.conf
May  6 12:02:30 kapacitor01 kapacitord: run: open server: open service *task_store.Service: no key exists
May  6 12:02:30 kapacitor01 systemd: kapacitor.service: main process exited, code=exited, status=1/FAILURE
May  6 12:02:30 kapacitor01 systemd: Unit kapacitor.service entered failed state.
May  6 12:02:30 kapacitor01 systemd: kapacitor.service failed.
May  6 12:02:30 kapacitor01 systemd: kapacitor.service holdoff time over, scheduling restart.
May  6 12:02:30 kapacitor01 systemd: Stopped Time series data processing engine..
```

Any help would be appreciated.

Kr,
Stefan
