### ISSUE TITLE
Panic on over UDF

### ISSUE THREAD

**Issue by Nexy3gpp** [influxdata/kapacitor#2539]
I get an error: 

panic: send on closed channel

goroutine 1744 [running]:
github.com/influxdata/kapacitor/edge.(*channelEdge).Collect(0xc004d4ddd0, 0x7f8ba5e7d7a8, 0xc2f52e6cf0, 0x407b03, 0xc00599e180)
        /root/go/src/github.com/influxdata/kapacitor/edge/edge.go:58 +0xc3
github.com/influxdata/kapacitor/edge.(*streamStatsEdge).Collect(0xc003c43bc0, 0x7f8ba5e7d7a8, 0xc2f52e6cf0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/edge/stats.go:207 +0x4b
github.com/influxdata/kapacitor/edge.Forward(0xc0012d8260, 0x1, 0x1, 0x7f8ba5e7d7a8, 0xc2f52e6cf0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/edge/forwarding.go:104 +0x72
github.com/influxdata/kapacitor.(*UDFNode).runUDF.func2(0xc0029a77c0, 0xc006342c00)
        /root/go/src/github.com/influxdata/kapacitor/udf.go:96 +0xc1
created by github.com/influxdata/kapacitor.(*UDFNode).runUDF
        /root/go/src/github.com/influxdata/kapacitor/udf.go:93 +0x146

I use UDF without socket. 
The handler closing i'm using the standard:
// Stop the handler gracefully.
func (a *objectHandler) Stop() {
    close(a.agent.Responses)
}

The error occurs when processing a large number of tags at the time of changing the severity level. 
Kapacitor version 1.5.2

**Comment by docmerlin** [comment]
This sounds like it may be a race between recreating the UDF and processing the data.

**Comment by Nexy3gpp** [comment]
UDF timeout and other config things don't help
