### ISSUE TITLE
Kapacitor panics when `|mean()`ing a measurement if there are empty values within the window period

### ISSUE THREAD

**Issue by glinton** [influxdata/kapacitor#498]
Kapacitor panics when `|mean()`ing a measurement if there are empty values within the window period.

Sysinfo
```sh
$ uname -a
Linux tester 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ kapacitord version
Kapacitor 0.12.0 (git: master 32d4d1b8f688e2d310f4e9413b3fe6ac3ef73c70)
# installed kapacitor_0.12.0-1_amd64.deb from downloads page
```

Stacktrace
```
panic: interface conversion: interface is nil, not float64

goroutine 40 [running]:
panic(0xc06660, 0xc82028c9c0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/kapacitor.(*floatPointAggregator).AggregateBatch(0xc8200ba0c0, 0xc82023af60)
        /root/go/src/github.com/influxdata/kapacitor/influxql.gen.go:41 +0x1ec
github.com/influxdata/kapacitor.(*InfluxQLNode).runBatchInfluxQL(0xc82023c2d0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/influxql.go:137 +0x458
github.com/influxdata/kapacitor.(*InfluxQLNode).runInfluxQLs(0xc82023c2d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/influxql.go:37 +0x83
github.com/influxdata/kapacitor.(*InfluxQLNode).(github.com/influxdata/kapacitor.runInfluxQLs)-fm(0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/influxql.go:28 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc82023c2d0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:128 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:129 +0x53
```

Task
```
$ kapacitor show cpu_test
Name: cpu_test
Error: 
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["statistics"."2_days"]
TICKscript:
stream
    |from()
        .measurement('metrics')
    |window()
        .period(20s)
        .every(20s)
    |mean('cpu_used')
    |alert()
        .id('cpu_used/{{ index .Tags "service" }}')
        .message('{{ .ID }} is {{ .Level }} value:{{ index .Fields "cpu_used" }}')
        .crit(lambda: "mean" > 0.001)
        .log('/tmp/alerts.log')



DOT:
digraph cpu_test {
graph [throughput="0.00 points/s"];

srcstream0 [avg_exec_time_ns="0" ];
srcstream0 -> stream1 [processed="4"];

stream1 [avg_exec_time_ns="629ns" ];
stream1 -> window2 [processed="4"];

window2 [avg_exec_time_ns="0" ];
window2 -> mean3 [processed="0"];

mean3 [avg_exec_time_ns="0" ];
mean3 -> alert4 [processed="0"];

alert4 [alerts_triggered="0" avg_exec_time_ns="0" ];
}
```

Data sample
```
InfluxDB shell 0.12.2
> use statistics
Using database statistics
> select * from metrics limit 2
name: metrics
-------------
time                    cpu_used        host            ram_used        service
1461950294743857288     0.0021          lester.tester                   web1
1461950294743924037                     lester.tester   0.6047          
```

Obviously, as soon as I stopped adding "ram_used" separately, kapacitor didn't panic.

**Comment by nhproject** [comment]
+1
It seems similar and related to my open issue:
https://github.com/influxdata/kapacitor/issues/499

**Comment by cnelissen** [comment]
+1 same problem here.

Kapacitor should silently skip fields/tags that either do not exist or contain a null value.
