### ISSUE TITLE
panic: interface conversion: interface is nil, not float64

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#499]
Hi 

I'm using Kapacitor 0.12.0,
I recently started to get panic errors with Kapacitor:

```
panic: interface conversion: interface is nil, not float64

goroutine 296 [running]:
panic(0xc19100, 0xc827ebe340)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/kapacitor.(*floatPointBulkAggregator).AggregateBatch(0xc829048480, 0xc8211e2000)
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/influxql.gen.go:78 +0x23b
github.com/influxdata/kapacitor.(*InfluxQLNode).runBatchInfluxQL(0xc8202d70e0, 0x0, 0x0)
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/influxql.go:137 +0x458
github.com/influxdata/kapacitor.(*InfluxQLNode).runInfluxQLs(0xc8202d70e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/influxql.go:37 +0x83
github.com/influxdata/kapacitor.(*InfluxQLNode).(github.com/influxdata/kapacitor.runInfluxQLs)-fm(0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/influxql.go:28 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc8202d70e0, 0x0, 0x0, 0x0)
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/node.go:128 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
	/tmp/kapacitor/src/github.com/influxdata/kapacitor/node.go:129 +0x53
```

where afterwards Kapacitor stops.

Any idea why is it happening?

Nitz

**Comment by cnelissen** [comment]
+1
