### ISSUE TITLE
Panic on Windows during record

### ISSUE THREAD

**Issue by andycarlsonuk** [influxdata/kapacitor#902]
I suspect that Windows is not well supported or widely used but the binary is available so I gave it a try. Some things worked for me but not enough to create usable alerts. I've tried 0.13.0, 0.13.1 and 1.0.0 with similar results. The same things work fine on a Linux VM.

Here is one example of a panic...

E:\kapacitor-1.0.0-1>kapacitor show amdocs_cpu
ID: amdocs_cpu
Error:
Template:
Type: batch
Status: disabled
Executing: false
Created: 14 Sep 16 15:57 BST
Modified: 14 Sep 16 16:13 BST
LastEnabled: 01 Jan 01 00:00 UTC
Databases Retention Policies: ["amdocs"."default"]
TICKscript:
batch
    |query('''
        SELECT mean(totalpct)
        FROM "amdocs"."default"."sar_cpu"
    ''')
        .period(1h)
        .every(1h)
        .groupBy(time(20m), 'host')
    |alert()
        .crit(lambda: "mean" > 25)
        .log('e:\temp\alerts.log')

DOT:
digraph amdocs_cpu {
query1 -> alert2;
}

E:\kapacitor-1.0.0-1>kapacitor record batch -task amdocs_cpu -past 24h
Post http://localhost:9092/kapacitor/v1/recordings/batch: read tcp [::1]:63565->[::1]:9092: wsarecv: An existing connection was forcibly closed by the remote host.

Server output...

2016/09/14 16:13:12 Using configuration at: kapacitor.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x59cc5f]

goroutine 58 [running]:
panic(0xd81ae0, 0xc082006080)
        /usr/local/go/src/runtime/panic.go:481 +0x3f4
github.com/influxdata/kapacitor/services/replay.(_Service).saveBatchRecording(0xc0820c5ce0, 0x0, 0x0, 0xc0822082c8, 0x1, 0x1, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:1392 +0x5f
github.com/influxdata/kapacitor/services/replay.(_Service).doRecordBatch.func1(0xc082223260, 0xc0820c5ce0, 0x0, 0x0, 0xc0822082c8, 0x1, 0x1)
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:1297 +0x64
created by github.com/influxdata/kapacitor/services/replay.(*Service).doRecordBatch
        /root/go/src/github.com/influxdata/kapacitor/services/replay/service.go:1298 +0x19d

The config is unchanged from the distribution except for...

[replay]
  dir = "E:\kapacitor-1.0.0-1\replay"
[task]
  dir = "E:\kapacitor-1.0.0-1\tasks"
[storage]
  boltdb = "E:\kapacitor-1.0.0-1\kapacitor.db"

**Comment by andycarlsonuk** [comment]
The backslashes in the above text shown by GitHub are actually double backslashes in my files. I guess I should have posted four backslashes. Sorry for any confusion.
